// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACF7oUHCKcvvaudjHrjo0daeAs6Cctedw',
    appId: '1:137493865426:web:6b4f8e801ea78f91185e0b',
    messagingSenderId: '137493865426',
    projectId: 'taskmanager-fc6ca',
    authDomain: 'taskmanager-fc6ca.firebaseapp.com',
    storageBucket: 'taskmanager-fc6ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRtBxATGYTDFaAVEFIm5ifYftOrpveBVM',
    appId: '1:137493865426:android:c26a2a2307236569185e0b',
    messagingSenderId: '137493865426',
    projectId: 'taskmanager-fc6ca',
    storageBucket: 'taskmanager-fc6ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz64852WpNyQUiUcLQVectaQ5J-FFn3x0',
    appId: '1:137493865426:ios:073789b77552dd9d185e0b',
    messagingSenderId: '137493865426',
    projectId: 'taskmanager-fc6ca',
    storageBucket: 'taskmanager-fc6ca.appspot.com',
    iosClientId: '137493865426-7gmdgak8r7ca3fn2bsbtn53c2j11c2dm.apps.googleusercontent.com',
    iosBundleId: 'com.example.systemforschool',
  );
}
